spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://localhost:4300"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
              - OPTIONS
            allowCredentials: true
            exposedHeaders:       # 👈 permet à Angular de lire ces headers
              - Content-Disposition
              - Content-Type

      routes:
        - id: notification-talent-service-custom
          uri: lb://NOTIFICATION-TALENT-SERVICE
          predicates:
            - Path=/notification-talent-service/api/v1/notifications/**

        - id: cv-download-service
          uri: lb://CANDIDAT-SERVICE
          predicates:
            - Path=/candidat-service/api/v1/cvs/download/**
          filters:
            - AddResponseHeader=Access-Control-Expose-Headers, Content-Disposition, Content-Type
